from aos.db.migrations import (
    _001_initial_schema,
    _002_create_auth_tables,
    _003_create_agri_tables,
    _004_create_transport_tables,
    _005_create_community_tables,
    _006_telegram_users,
    _007_domain_aware_users,
    _008_transport_v2_schema,
    _009_community_members,
    _010_broadcast_tables,
    _011_community_activity_log,
    _012_community_admin_rbac,
    _013_ensure_base_roles,
    _014_community_invite_slugs,
    _015_community_codes,
    _016_institution_core,
    _017_group_memberships,
    _018_attendance_finance,
    _019_audit_logs,
    _020_retry_queue,
    _021_institution_types,
)

# Strict migration registry
MIGRATIONS = [
    _001_initial_schema,
    _002_create_auth_tables,
    _003_create_agri_tables,
    _004_create_transport_tables,
    _005_create_community_tables,
    _006_telegram_users,
    _007_domain_aware_users,
    _008_transport_v2_schema,
    _009_community_members,
    _010_broadcast_tables,
    _011_community_activity_log,
    _012_community_admin_rbac,
    _013_ensure_base_roles,
    _014_community_invite_slugs,
    _015_community_codes,
    _016_institution_core,
    _017_group_memberships,
    _018_attendance_finance,
    _019_audit_logs,
    _020_retry_queue,
    _021_institution_types,
]
